# Generated by Django 5.0 on 2023-12-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repetitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('education', models.CharField(max_length=200)),
            ],
        ),
    ]
