# Generated by Django 5.0 on 2023-12-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetitor',
            name='experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
