# Generated by Django 4.2.3 on 2023-12-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_repetitor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repetitor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
