# Generated by Django 4.2.3 on 2023-12-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_repetitor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetitor',
            name='cost',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repetitor',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
